Another avg_weight solution
gavin1332/samples pull request #1
Opened 2020-06-05 12:24 UTC by hutuxian

Just for reference

2020-06-05 13:43 UTC, gavin1332 requested changes

2020-06-05 13:43 UTC, gavin1332 commented on paddlebox/avg_weight_better.py
> +    for e in avg_list:
不是每个minibatch都拷贝，是每个pass拷贝

2020-06-06 02:14 UTC, hutuxian commented on paddlebox/avg_weight_better.py
> +    for e in avg_list:
Just example，will add comment to show it more clear

2020-06-06 02:20 UTC, hutuxian commented on paddlebox/avg_weight_better.py
> +    for e in avg_list:
update done

2020-06-08 01:14 UTC, gavin1332 approved these changes
LGTM

2020-06-08 01:14 UTC, merged